### ISSUE TITLE
Surface selection issue

### ISSUE THREAD

**Issue by FrancoisLasson** [ros-industrial-attic/godel#55]
Beginner with Godel,
I'm trying to use the godel_surface_detection package.

I launch : $ roslaunch godel_surface_detection robot_blending.launch
and I try to « Scan and Find » some surfaces.

Even though "Selected surface clusters" are found, I don't succeed in select these surfaces. 
Could you explain me the solution to select them?

log files : https://mega.co.nz/#!BYAVSZha!zYmWa4sig1CgIwDRZehJvpxYjebqeMSbtc7cr1JVeTs

Thank you, 
François.

![capture du 2015-03-24 16 36 42](https://cloud.githubusercontent.com/assets/11289891/6805580/ff87a978-d243-11e4-8c6c-6d7a2245bc33.png)

**Comment by Jmeyer1292** [comment]
I'll look into this issue today.

**Comment by Jmeyer1292** [comment]
There's a missing return statement on here:
https://github.com/ros-industrial-consortium/godel/blob/hydro-devel/godel_surface_detection/src/detection/surface_detection.cpp#L833-L834

It should have "return true" before the closing brace of the function. Try it out and let me know. This will be fixed in pull requests I'm working on right now.

**Comment by FrancoisLasson** [comment]
Your solution fixes the problem. From now on, all surfaces can be selected. 
Thank you.

![capture du 2015-03-26 10 22 01](https://cloud.githubusercontent.com/assets/11289891/6843316/fc0dd6aa-d3a1-11e4-8d0c-61656806e2e2.png)

**Comment by Jmeyer1292** [comment]
@jrgnicho This should be closed.

**Comment by Jmeyer1292** [comment]
Addressed by #65. Thank you for bringing this issue to light.

**Comment by jrgnicho** [comment]
Address in #65
